# Spring properties
spring:
  data:
    cassandra:
      keyspace-name: customer_journey
      contact-points: illin1111

# Discovery Server Access
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: false
      sensitive: false
      registerWithEureka: true
      fetchRegistry: true
    instance:
      metadataMap:
        instanceId: customer-journey:${spring.application.instance_id:${random.value}}  #a random instance id
ribbon:
    eureka:
        enabled: true


# For multiple instances you should override this with on server boot using --server.port=9001 for example  (or any other port number)
#server:
#  port: 10001
logging:
  level:
    org.springframework.security: INFO

#custom settings
api:
  version: v1
  
ensemble:
  memoServiceURL: https://memo-services-app/memo-list/v1/
