# Spring properties
spring:
  data:
    cassandra:
      keyspace-name: customer_journey
      contact-points: illin1111
  cloud:
    stream:
      bindings:
        output:
          destination: memo
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

# Discovery Server Access
eureka:
  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
      registerWithEureka: true
      fetchRegistry: true
    instance:
      metadataMap:
        instanceId: customer-journey:${spring.application.instance_id:${random.value}}  #a random instance id
      appname: customer-journey-app
      prefer-ip-address: true

ribbon:
    eureka:
        enabled: true


# For multiple instances you should override this with on server boot using --server.port=9001 for example  (or any other port number)
server:
  port: 10001
logging:
  level:
    org.springframework.security: INFO

#custom settings
api:
  version: v1

security:
  user:
    password: spring123
